// data_master/ports.js - game port definitions for L.A.V.A.
// WPI fields sourced from NGA World Port Index (Pub 150, UpdatedPub150.csv), build-time join.
// lat/lon are real-world coordinates; nx/ny are the existing stylized canvas map positions
// (DO NOT change nx/ny - the canvas renders from them). Generated by build_ports.py,
// then WPI joins verified/corrected against the CSV.
// Array ORDER is significant: map.js connections reference ports by index.
// NOTE: ports with no WPI entry carry ESTIMATED data instead, marked {"estimated": true,
// "wpiNumber": null}. These are regional/size approximations (harborType, harborSize,
// channelDepthM, anchorageDepthM only) — do NOT treat them as authoritative WPI values.
const PORTS = [
  { name: "Yokosuka", type: "base", nx: 0.97, ny: 0.03,
    lat: 35.283333, lon: 139.666667,
    wpi: {"wpiNumber": 61400, "country": "Japan", "harborSize": "Medium", "harborType": "Coastal (Natural)", "shelter": "Good", "channelDepthM": 14, "anchorageDepthM": 23.2, "cargoPierDepthM": 9.4, "maxVesselDraftM": 10, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Sasebo", type: "base", nx: 0.7, ny: 0.15,
    lat: 33.166667, lon: 129.716667,
    wpi: {"wpiNumber": 62380, "country": "Japan", "harborSize": "Medium", "harborType": "Coastal (Natural)", "shelter": "Good", "channelDepthM": 11, "anchorageDepthM": 23.2, "cargoPierDepthM": 11, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Okinawa", type: "site", nx: 0.64, ny: 0.47,
    lat: 26.216667, lon: 127.683333,
    wpi: {"wpiNumber": 62500, "country": "Japan", "harborSize": "Small", "harborType": "Coastal (Breakwater)", "shelter": "Good", "channelDepthM": 12.5, "anchorageDepthM": 12.5, "cargoPierDepthM": 14, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Kunsan", type: "base", nx: 0.63, ny: 0.08,
    lat: 35.983333, lon: 126.616667,
    wpi: {"wpiNumber": 60330, "country": "South Korea", "harborSize": "Small", "harborType": "River (Natural)", "shelter": "Fair", "channelDepthM": 9.4, "anchorageDepthM": 9.4, "cargoPierDepthM": 11, "maxVesselDraftM": 14, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  // Batanes = WPI "Basco" (#57970), the Batanes provincial port. Was incorrectly null.
  { name: "Batanes", type: "site", nx: 0.42, ny: 0.57,
    lat: 20.45, lon: 121.966667,
    wpi: {"wpiNumber": 57970, "country": "Philippines", "harborSize": "Very Small", "harborType": "Coastal (Natural)", "shelter": "Fair", "channelDepthM": 11, "anchorageDepthM": 23.2, "cargoPierDepthM": 3.4, "maxVesselDraftM": 0, "tugs": "Unknown", "pilotage": "Unknown", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "No"}} },
  // Subic Bay = WPI #58395. Record was previously (mis-)attached to Camilo Osias.
  { name: "Subic Bay", type: "site", nx: 0.35, ny: 0.7,
    lat: 14.8, lon: 120.266667,
    wpi: {"wpiNumber": 58395, "country": "Philippines", "harborSize": "Medium", "harborType": "Coastal (Natural)", "shelter": "Excellent", "channelDepthM": 23.2, "anchorageDepthM": 23.2, "cargoPierDepthM": 11, "maxVesselDraftM": 13, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "Unknown"}} },
  { name: "Palawan", type: "site", nx: 0.28, ny: 1.02,
    lat: 9.733333, lon: 118.733333,
    wpi: {"wpiNumber": 59270, "country": "Philippines", "harborSize": "Small", "harborType": "Coastal (Natural)", "shelter": "Good", "channelDepthM": 23.2, "anchorageDepthM": 17.1, "cargoPierDepthM": 7.9, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "No"}} },
  { name: "Guam", type: "base", nx: 0.9, ny: 1.02,
    lat: 13.45, lon: 144.616667,
    wpi: {"wpiNumber": 56550, "country": "Guam", "harborSize": "Medium", "harborType": "Coastal (Breakwater)", "shelter": "Good", "channelDepthM": 11, "anchorageDepthM": 23.2, "cargoPierDepthM": 7.9, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "No"}} },
  // Camilo Osias (Port Irene, Santa Ana) is NOT in the WPI. The #58395 record that was
  // here actually belongs to Subic Bay (above); set to null.
  { name: "Camilo Osias", type: "base", nx: 0.45, ny: 0.86,
    lat: 18.5, lon: 122.15,
    wpi: {"wpiNumber": null, "estimated": true, "harborType": "Coastal (Natural)", "harborSize": "Small", "channelDepthM": 15, "anchorageDepthM": 12.5, "basis": "est. from Port San Vicente (~3 km, same locale)"} },
  // Penghu = WPI "Peng-Hu Kang" / Ma-kung (#57950). Coords corrected to WPI position.
  { name: "Penghu", type: "site", nx: 0.36, ny: 0.61,
    lat: 23.583333, lon: 119.533333,
    wpi: {"wpiNumber": 57950, "country": "Taiwan", "harborSize": "Small", "harborType": "Coastal (Natural)", "shelter": "Fair", "channelDepthM": 7.9, "anchorageDepthM": 7.9, "cargoPierDepthM": 4.9, "maxVesselDraftM": 0, "tugs": "Unknown", "pilotage": "Unknown", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  // Paracel Islands - not in WPI (nearest charted port is Sanya, ~394 km away).
  { name: "Paracel Islands", type: "site", nx: 0.1, ny: 0.96,
    lat: 16.6, lon: 112.7,
    wpi: {"wpiNumber": null, "estimated": true, "harborType": "Coastal (Breakwater)", "harborSize": "Very Small", "channelDepthM": 8, "anchorageDepthM": 6, "basis": "est. constructed island harbor; Hainan analogs (Sanya/Haikou)"} },
  // Pengjia Islet (Agincourt I.) - not in WPI; real-world coordinates supplied.
  { name: "Pengjia", type: "site", nx: 0.46, ny: 0.49,
    lat: 25.628, lon: 122.078,
    wpi: {"wpiNumber": null, "estimated": true, "harborType": "Open Roadstead", "harborSize": "Very Small", "channelDepthM": 5, "anchorageDepthM": 10, "basis": "est. islet landing only; no developed harbor (Keelung not comparable)"} },
  // Pratas / Dongsha atoll - not in WPI; real-world coordinates supplied.
  // (The similarly-named WPI "Dongshan" is a different port on the Fujian coast.)
  { name: "Pratas", type: "site", nx: 0.25, ny: 0.75,
    lat: 20.7, lon: 116.717,
    wpi: {"wpiNumber": null, "estimated": true, "harborType": "Coastal (Natural)", "harborSize": "Very Small", "channelDepthM": 6, "anchorageDepthM": 8, "basis": "est. atoll outpost pier; Shantou/Huizhou small-harbor analogs"} },
  // Lanyu (Orchid Island) - not in WPI; real-world coordinates supplied.
  { name: "Lanyu", type: "site", nx: 0.43, ny: 0.68,
    lat: 22.05, lon: 121.52,
    wpi: {"wpiNumber": null, "estimated": true, "harborType": "Coastal (Natural)", "harborSize": "Very Small", "channelDepthM": 6, "anchorageDepthM": 8, "basis": "est. Kaiyuan ferry harbor; Peng-Hu Kang/Basco analogs"} },
  // Iriomote/Ishigaki = WPI "Ishigaki" (#62520). Port is on Ishigaki (Iriomote has none).
  { name: "Iriomote Ishigaki", type: "site", nx: 0.52, ny: 0.56,
    lat: 24.333333, lon: 124.166667,
    wpi: {"wpiNumber": 62520, "country": "Japan", "harborSize": "Very Small", "harborType": "Open Roadstead", "shelter": "Fair", "channelDepthM": 7.9, "anchorageDepthM": 21.6, "cargoPierDepthM": 9.4, "maxVesselDraftM": 0, "tugs": "Unknown", "pilotage": "No", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Unknown", "swell": "Unknown", "ice": "Unknown"}} }
];