// data_master/ports.js - game port definitions for L.A.V.A.
// WPI fields sourced from NGA World Port Index (Pub 150, UpdatedPub150.csv), build-time join.
// lat/lon are real-world coordinates; nx/ny are the existing stylized canvas map positions
// (DO NOT change nx/ny - the canvas renders from them). Generated by build_ports.py.
// Array ORDER is significant: map.js connections reference ports by index 0-10.
const PORTS = [
  { name: "Yokosuka", type: "base", nx: 0.97, ny: 0.03,
    lat: 35.283333, lon: 139.666667,
    wpi: {"wpiNumber": 61400, "country": "Japan", "harborSize": "Medium", "harborType": "Coastal (Natural)", "shelter": "Good", "channelDepthM": 14, "anchorageDepthM": 23.2, "cargoPierDepthM": 9.4, "maxVesselDraftM": 10, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Sasebo", type: "base", nx: 0.7, ny: 0.15,
    lat: 33.166667, lon: 129.716667,
    wpi: {"wpiNumber": 62380, "country": "Japan", "harborSize": "Medium", "harborType": "Coastal (Natural)", "shelter": "Good", "channelDepthM": 11, "anchorageDepthM": 23.2, "cargoPierDepthM": 11, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Okinawa", type: "site", nx: 0.64, ny: 0.47,
    lat: 26.216667, lon: 127.683333,
    wpi: {"wpiNumber": 62500, "country": "Japan", "harborSize": "Small", "harborType": "Coastal (Breakwater)", "shelter": "Good", "channelDepthM": 12.5, "anchorageDepthM": 12.5, "cargoPierDepthM": 14, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Kunsan", type: "base", nx: 0.63, ny: 0.08,
    lat: 35.983333, lon: 126.616667,
    wpi: {"wpiNumber": 60330, "country": "South Korea", "harborSize": "Small", "harborType": "River (Natural)", "shelter": "Fair", "channelDepthM": 9.4, "anchorageDepthM": 9.4, "cargoPierDepthM": 11, "maxVesselDraftM": 14, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "No", "swell": "No", "ice": "No"}} },
  { name: "Batanes", type: "site", nx: 0.42, ny: 0.57,
    lat: 20.45, lon: 121.97,
    wpi: null },
  { name: "Subic Bay", type: "site", nx: 0.35, ny: 0.7,
    lat: 14.8, lon: 120.266667,
  },
  { name: "Palawan", type: "site", nx: 0.28, ny: 1.02,
    lat: 9.733333, lon: 118.733333,
    wpi: {"wpiNumber": 59270, "country": "Philippines", "harborSize": "Small", "harborType": "Coastal (Natural)", "shelter": "Good", "channelDepthM": 23.2, "anchorageDepthM": 17.1, "cargoPierDepthM": 7.9, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "No"}} },
  { name: "Guam", type: "base", nx: 0.9, ny: 1.02,
    lat: 13.45, lon: 144.616667,
    wpi: {"wpiNumber": 56550, "country": "Guam", "harborSize": "Medium", "harborType": "Coastal (Breakwater)", "shelter": "Good", "channelDepthM": 11, "anchorageDepthM": 23.2, "cargoPierDepthM": 7.9, "maxVesselDraftM": 0, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "No"}} },
  { name: "Camilo Osias", type: "base", nx: 0.45, ny: 0.86,
    lat: 18.5, lon: 122.15,
    wpi: {"wpiNumber": 58395, "country": "Philippines", "harborSize": "Medium", "harborType": "Coastal (Natural)", "shelter": "Excellent", "channelDepthM": 23.2, "anchorageDepthM": 23.2, "cargoPierDepthM": 11, "maxVesselDraftM": 13, "tugs": "Yes", "pilotage": "Yes", "roro": "Unknown", "container": "Unknown", "restrictions": {"tide": "Yes", "swell": "Yes", "ice": "Unknown"}} },
  {
    name: "Penghu", type: "site", nx: 0.36, ny: 0.61,
    lat: 23.5, lon: 119.2,
    wpi: null
  },
  {
    name: "Paracel Islands", type: "site", nx: 0.1, ny: 0.96,
    lat: 16.6, lon: 112.7,
    wpi: null
  },
  {
    name: "Pengjia", type: "site", nx: 0.46, ny: 0.49,
    wpi: null
  },
  {
    name: "Pratas", type: "site", nx: 0.25, ny: 0.75, 
    wpi: null
  },
  {
    name: "Lanyu", type: "site", nx: 0.43, ny: 0.68,
    wpi: null
  },
  {
    name: "Iriomote Ishigaki", type: "site", nx: 0.52, ny: 0.56,
    wpi: null
  }
];
