# One-off BUILD-TIME script. Joins map.js port array with NGA WPI (UpdatedPub150.csv)
# and emits data_master/ports.js. Not loaded at runtime. (Node unavailable; Python used.)
import csv, json, sys

PORTS = [
    {"name": "Yokosuka", "nx": 0.97, "ny": 0.03, "type": "base",
     "inventory": {"CARGO-034": 40, "CARGO-033": 30, "CARGO-004": 30, "CARGO-008": 20, "CARGO-010": 10, "CARGO-028": 5, "CARGO-001": 5}},
    {"name": "Sasebo", "nx": 0.7, "ny": 0.15, "type": "base",
     "inventory": {"CARGO-010": 4, "CARGO-013": 30, "CARGO-001": 30, "CARGO-006": 20, "CARGO-028": 20, "CARGO-004": 5, "CARGO-033": 5}},
    {"name": "Okinawa", "nx": 0.64, "ny": 0.47, "type": "site"},
    {"name": "Kunsan", "nx": 0.63, "ny": 0.08, "type": "base",
     "inventory": {"CARGO-013": 3, "CARGO-008": 30, "CARGO-028": 30, "CARGO-033": 25, "CARGO-010": 5, "CARGO-004": 15, "CARGO-001": 5}},
    {"name": "Batanes", "nx": 0.42, "ny": 0.57, "type": "site"},
    {"name": "Subic Bay", "nx": 0.35, "ny": 0.70, "type": "base",
     "inventory": {"CARGO-013": 3, "CARGO-008": 30, "CARGO-028": 30, "CARGO-033": 20, "CARGO-010": 5, "CARGO-004": 10, "CARGO-001": 5}},
    {"name": "Palawan", "nx": 0.28, "ny": 1.02, "type": "site"},
    {"name": "Guam", "nx": 0.9, "ny": 1.02, "type": "base",
     "inventory": {"CARGO-013": 5, "CARGO-001": 5, "CARGO-006": 15, "CARGO-004": 30, "CARGO-027": 25, "CARGO-010": 10, "CARGO-034": 10, "CARGO-028": 15}},
    {"name": "Camilo Osias", "nx": 0.45, "ny": 0.86, "type": "site"},
    {"name": "Kyogamisaki", "nx": 0.87, "ny": 0.0, "type": "site"},
    {"name": "Mujuk", "nx": 0.67, "ny": 0.036, "type": "site"},
]

WPI_MATCH = {
    "Yokosuka": "Yokosuka Ko", "Sasebo": "Sasebo", "Okinawa": "Naha Ko",
    "Kunsan": "Kunsan", "Subic Bay": "Subic Bay", "Palawan": "Puerto Princesa",
    "Guam": "Apra Harbor",
}
NO_WPI_COORDS = {
    "Batanes": (20.45, 121.97), "Camilo Osias": (18.50, 122.15),
    "Kyogamisaki": (35.77, 135.22), "Mujuk": (35.92, 129.55),
}

def num(v):
    if v is None: return None
    t = str(v).strip()
    if t == "": return None
    try:
        f = float(t)
        return int(f) if f.is_integer() else f
    except ValueError:
        return None

def s(v):
    if v is None: return None
    t = str(v).strip()
    return None if t == "" else t

with open("data_master/UpdatedPub150.csv", encoding="utf-8-sig", newline="") as f:
    reader = csv.DictReader(f)
    by_name = {}
    for row in reader:
        k = row["Main Port Name"]
        if k not in by_name:
            by_name[k] = row

for p in PORTS:
    if p["name"] in WPI_MATCH:
        r = by_name[WPI_MATCH[p["name"]]]
        p["lat"] = num(r["Latitude"])
        p["lon"] = num(r["Longitude"])
        p["wpi"] = {
            "wpiNumber": num(r["World Port Index Number"]),
            "country": s(r["Country Code"]),
            "harborSize": s(r["Harbor Size"]),
            "harborType": s(r["Harbor Type"]),
            "shelter": s(r["Shelter Afforded"]),
            "channelDepthM": num(r["Channel Depth (m)"]),
            "anchorageDepthM": num(r["Anchorage Depth (m)"]),
            "cargoPierDepthM": num(r["Cargo Pier Depth (m)"]),
            "maxVesselDraftM": num(r["Maximum Vessel Draft (m)"]),
            "tugs": s(r["Tugs - Assistance"]),
            "pilotage": s(r["Pilotage - Available"]),
            "roro": s(r["Facilities - Ro-Ro"]),
            "container": s(r["Facilities - Container"]),
            "restrictions": {
                "tide": s(r["Entrance Restriction - Tide"]),
                "swell": s(r["Entrance Restriction - Heavy Swell"]),
                "ice": s(r["Entrance Restriction - Ice"]),
            },
        }
    else:
        p["lat"], p["lon"] = NO_WPI_COORDS[p["name"]]
        p["wpi"] = None

def fmt_inv(inv):
    return "{ " + ", ".join(f'"{k}": {v}' for k, v in inv.items()) + " }"

def fmt_wpi(w):
    return "null" if w is None else json.dumps(w)

out = (
    "// data_master/ports.js - game port definitions for L.A.V.A.\n"
    "// WPI fields sourced from NGA World Port Index (Pub 150, UpdatedPub150.csv), build-time join.\n"
    "// lat/lon are real-world coordinates; nx/ny are the existing stylized canvas map positions\n"
    "// (DO NOT change nx/ny - the canvas renders from them). Generated by build_ports.py.\n"
    "// Array ORDER is significant: map.js connections reference ports by index 0-10.\n"
    "const PORTS = [\n"
)
for p in PORTS:
    line = f'  {{ name: {json.dumps(p["name"])}, type: {json.dumps(p["type"])}, nx: {p["nx"]}, ny: {p["ny"]},'
    if "inventory" in p:
        line += f'\n    inventory: {fmt_inv(p["inventory"])},'
    line += f'\n    lat: {p["lat"]}, lon: {p["lon"]},'
    line += f'\n    wpi: {fmt_wpi(p["wpi"])} }},'
    out += line + "\n"
out += "];\n"

if len(sys.argv) > 1 and sys.argv[1] == "--write":
    with open("data_master/ports.js", "w", encoding="utf-8") as f:
        f.write(out)
    sys.stderr.write("WROTE data_master/ports.js\n")
else:
    sys.stdout.write(out)

sys.stderr.write("\n--- ACCEPTANCE ---\n")
sys.stderr.write(f"count: {len(PORTS)}\n")
sys.stderr.write("order: " + ", ".join(p["name"] for p in PORTS) + "\n")
sys.stderr.write("all numeric lat/lon: " + str(all(isinstance(p["lat"], (int, float)) and isinstance(p["lon"], (int, float)) for p in PORTS)) + "\n")
sys.stderr.write("matched w/ wpi: " + ", ".join(p["name"] for p in PORTS if p["wpi"]) + "\n")
sys.stderr.write("null wpi: " + ", ".join(p["name"] for p in PORTS if p["wpi"] is None) + "\n")
bat = next(p for p in PORTS if p["name"] == "Batanes")
sys.stderr.write(f"Batanes lat: {bat['lat']} (expect ~20.45, NOT ~13.75)\n")
